---
language: node_js
node_js:
  - "9"

sudo: false
dist: trusty

cache:
  yarn: true

env:
  global:
    - NODE_DEBUG=dns-over-https

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install --no-lockfile --non-interactive

script:
  - yarn test
